crm_user:
    resource: "@CRMUserBundle/Resources/config/routing.yml"
    prefix:   /

crm_tools:
    resource: "@CRMToolsBundle/Resources/config/routing.yml"
    prefix:   /

aerialship_saml_sp_bundle:
    resource: "@AerialShipSamlSPBundle/Resources/config/routing.yml"