# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        CRM\UserBundle\Entity\User: plaintext

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                 users:
                     user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                     admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        custom:
            id: user.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
             pattern:   ^/
             anonymous: true
             provider:  custom
             form_login:
                 login_path: login
                 check_path: login_check
             form_login_ldap:
                 login_path: login
                 check_path: login_check
                 service: ldap
                 dn_string: '{username}@pvcp.intra'
                 csrf_token_generator: security.csrf.token_manager
             logout:
                 path:   logout
                 target: /
             aerial_ship_saml_sp:
                 login_path: /saml/sp/login
                 local_logout_path: /logout
                 metadata_path: /saml/sp/FederationMetadata.xml
                 default_target_path: /
                 provider: in_memory
                 services:
                     somename:
                         idp:
                             file: "@CRMToolsBundle/Resources/idp-FederationMetadata.xml"
                         sp:
                             config:
                                 entity_id: https://frccesvapd01.pvcp.intra/crm_tools/web/app.php/saml/sp/login
             logout:
                 path: /logout


