<?php

namespace CRM\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CLI_DATA_IMPORTSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CLI_DATA_IMPORTSRepository extends EntityRepository
{
    public function getProcessedFilesData($date_array, $filter = null){

        $result_array = array();
        foreach($date_array as $current_date){

            $sql = "SELECT 
                        FILE_NAME,
                        GAME_NAME,
                        DATE_TRAITEMENT,
                        ERROR_LIST,
                        TOTAL,
                        case when nvl(\"INSERT\",0) = 0 then '0 (0%)' else \"INSERT\" || ' (' || trunc(100 * \"INSERT\" / case when TOTAL = '0' then '1' else total end,2) || '%)' end as \"INSERT\", 
	                    case when nvl(\"UPDATE\",0) = 0 then '0 (0%)' else \"UPDATE\" || ' (' || trunc(100 * \"UPDATE\" / case when TOTAL = '0' then '1' else total end,2) || '%)' end as \"UPDATE\", 
	                    case when nvl(\"REJECT\",0) = 0 then '0 (0%)' else \"REJECT\" || ' (' || trunc(100 * \"REJECT\" / case when TOTAL = '0' then '1' else total end,2) || '%)' end as \"REJECT\" 
                    FROM(
                        select
                            distinct  
                            imp.file_name, 
                            max(game_name) over (partition by imp.file_name) as game_name,
                            max(date_traitement) over (partition by imp.file_name) as date_traitement, 
                            decode(action,'REJET','REJECT', action) as action,
                            nbr_ligne,
                            error_list
                        from CLI_DATA_IMPORTS imp
                        left join 
                        (
                            select
                                file_name,
                                listagg(error_code || '(' || nb_error || ')',' ') within group (order by nb_error desc) as error_list
                            from
                            (
                                select 
                                    file_name,
                                    error_code,
                                    count(*) as nb_error
                                from
                                (
                                    select file_name, error_code from ERR_UPDATE_SUBSCRIPTION 
                                    union all
                                    select FILE_NAME, code_rejet from ERR_JEUX
                                    union all 
                                    select FILE_NAME, REJECT_CODE from ERR_APPENDING
                                )
                                group by file_name, error_code
                            )
                            group by file_name	
                        ) errors on errors.file_name = imp.file_name
                    )
                        pivot
                    (
                        max(nbr_ligne) for action in ('TOTAL' as \"TOTAL\",'INSERT' as \"INSERT\",'UPDATE' as \"UPDATE\",'REJECT' as \"REJECT\")
                    )
                    where  trunc(date_traitement) = TO_DATE('$current_date', 'YYYY-MM-DD') and file_name not like '%NEO_RC_REF_CONTACT_B2B%' $filter order by FILE_NAME";
//            echo $sql;
            $em = $this->getEntityManager();
            $query = $em->getConnection()->prepare($sql);
            $query->execute();
            $result = $query->fetchAll();
//            var_dump($result);
            $result_array[$current_date] = $result;
        }

        return $result_array;

    }
}
