<?php

namespace CRM\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CrmImportFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmImportFileRepository extends EntityRepository{

    public function getFilesImporToDisplay(){
//        $sqlGrpName = "SELECT DISTINCT groupName from crm_queries WHERE pageName = 'error_analysis'";
        $sql = "SELECT
                    crm_import_file.id,
                    fileName as file_name,
                    username,
                    hostname,
                    nbrLine as 'Row Count',
                    importDate,
                    crm_import_file.processDate,
                    tmp.to_be_processed as 'Total', 
                    isAdmin,
                    user_id
                FROM crm_import_file
                LEFT JOIN crm_users on crm_users.id= crm_import_file.user_id
                LEFT JOIN 
                (
                  SELECT
                  fileType AS file_type,
                  processDate,
                  SUM(nbrLine) AS to_be_processed
                  FROM crm_import_file
                  group by fileType, processDate
                ) 
                tmp ON tmp.file_type = crm_import_file.fileType AND tmp.processDate = crm_import_file.processDate
                WHERE crm_import_file.processDate >= now()";
        $em = $this->getEntityManager();
        $query = $em->getConnection()->prepare($sql);
        $query->execute();
        $result = $query->fetchAll();
        return $result;
    }

    public function getFileImport($fileName){
        $sql = "SELECT 1 from crm_import_file where fileName = '" . $fileName . "';";
        $em = $this->getEntityManager();
        $query = $em->getConnection()->prepare($sql);
        $query->execute();
        $result = $query->fetchAll();
        return $result;
    }

    public function getNbLine($file_date, $file_type){
        $sql = "SELECT IFNULL(sum(nbrLine),0) as NBR FROM crm_import_file where processDate = '" . $file_date . "' AND fileType = '" . $file_type . "';";

        $em = $this->getEntityManager();
        $query = $em->getConnection()->prepare($sql);
        $query->execute();
        $result = $query->fetchAll();

        return $result;
    }

    public function insertFileUpload($user_id, $file_name, $nb_lines, $import_date, $process_date, $file_type, $em){

        $sql = "INSERT INTO crm_import_file (user_id, fileName,nbrLine, importDate, processDate,FileType) VALUES ($user_id, '$file_name', $nb_lines, '$import_date', '$process_date', '$file_type')";
        $query = $em->getConnection()->prepare($sql);
        $query->execute();
    }

    public function deleteOneFile($file_id){

        $sql = "DELETE FROM crm_import_file WHERE id = " . $file_id . ";";
        $em = $this->getEntityManager();
        $query = $em->getConnection()->prepare($sql);
        $query->execute();

    }

}
