<?php

namespace CRM\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CrmLogErrorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmLogErrorsRepository extends EntityRepository
{
    public function getLogErrorsWithDates($dates_array){
        $logErrorsResult= array();
        rsort($dates_array);

        foreach ($dates_array as $day){
            $sql="SELECT errors.fileName, errors.errorCount, errors.errorText, ref.errorDescription	FROM crm_log_errors errors 
                  LEFT JOIN crm_ref_errors ref ON ref.jobName = errors.jobName AND (ref.errorText = errors.errorText or ref.errorText = '*')
	              WHERE fileDate ='".$day."'  order by case WHEN ref.errorText = '*' then 0 else 1 end desc, fileName";

            $em = $this->getEntityManager();
            $query = $em->getConnection()->prepare($sql);
            $query->execute();
            $result = $query->fetchAll();

            if($result){
                $logErrorsResult[$day]= $result;
            }
        }

        return $logErrorsResult;
    }
}
