<?php

namespace CRM\ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CrmUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrmUsersRepository extends EntityRepository
{
    public function getCurrentUser($currentHostname)
    {
        $sql = "SELECT * FROM crm_users WHERE hostName='" .$currentHostname."';";

//        echo $sql;die;
        $em = $this->getEntityManager();
        $query = $em->getConnection()->prepare($sql);
        $query->execute();
        $result = $query->fetchAll();
        return $result;
    }
}
